kind: Service # this is the service for the deployment. I'm exposing port 80 of the nginx container to port 8123
apiVersion: v1
metadata: 
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      name: http
      protocol: TCP
